module.exports = {
  'bg-n': 'background:none;',
  'bgc-t': 'background-color:transparent;',
  'bgi-n': 'background-image:none;',
  'bgr-n': 'background-repeat:no-repeat;',
  'bgr-x': 'background-repeat:repeat-x;',
  'bgr-y': 'background-repeat:repeat-y;',
  'bgr-sp': 'background-repeat:space;',
  'bgr-rd': 'background-repeat:round;',
  'bga-f': 'background-attachment:fixed;',
  'bga-s': 'background-attachment:scroll;',
  'bgbk-bb': 'background-break:bounding-box;',
  'bgbk-eb': 'background-break:each-box;',
  'bgbk-c': 'background-break:continuous;',
  bgcp: 'background-clip:padding-box;',
  'bgcp-bb': 'background-clip:border-box;',
  'bgcp-pb': 'background-clip:padding-box;',
  'bgcp-cb': 'background-clip:content-box;',
  'bgcp-nc': 'background-clip:no-clip;',
  'bgo-pb': 'background-origin:padding-box;',
  'bgo-bb': 'background-origin:border-box;',
  'bgo-cb': 'background-origin:content-box;',
  'bgsz-a': 'background-size:auto;',
  'bgsz-ct': 'background-size:contain;',
  'bgsz-cv': 'background-size:cover;',
};
