module.exports = {
  // 'cnt': 'content:'';',
  // 'cnt-n,': 'ct:n': 'content:normal;',
  // 'cnt-oq,': 'ct:oq': 'content:open-quote;',
  // 'cnt-noq,': 'ct:noq': 'content:no-open-quote;',
  // 'cnt-cq,': 'ct:cq': 'content:close-quote;',
  // 'cnt-ncq,': 'ct:ncq': 'content:no-close-quote;',
  // 'cnt-a,': 'ct:a': 'content:attr();',
  // 'cnt-c,': 'ct:c': 'content:counter();',
  // 'cnt-cs,': 'ct:cs': 'content:counters();',
  'q-n': 'quotes:none;',
  // 'q-ru': 'quotes:'\00AB'': ''\00BB'': ''\201E'': ''\201C';',
  // 'q-en': 'quotes:'\201C'': ''\201D'': ''\2018'': ''\2019';',
  'ol-n': 'outline:none;',
  'olw-tn': 'outline-width:thin;',
  'olw-m': 'outline-width:medium;',
  'olw-tc': 'outline-width:thick;',
  'ols-n': 'outline-style:none;',
  'ols-dt': 'outline-style:dotted;',
  'ols-ds': 'outline-style:dashed;',
  'ols-s': 'outline-style:solid;',
  'ols-db': 'outline-style:double;',
  'ols-g': 'outline-style:groove;',
  'ols-r': 'outline-style:ridge;',
  'ols-i': 'outline-style:inset;',
  'ols-o': 'outline-style:outset;',
  olc: 'outline-color:#000;',
  'olc-i': 'outline-color:invert;',
};
